# -*- coding: utf-8 -*-
"""cv 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMfFZ8Tfabl-CzaPn2EGP7eKrR1-uQpq
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_comparision(original,sobel,prewitt,canny):
  plt.figure(figsize=(12,10))

  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original Grayscale image')
  plt.axis('off')

  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title('Sobel Edge Detection')
  plt.axis('off')

  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title('Prewitt Edge Detection')
  plt.axis('off')

  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title('Canny Edge Detection')
  plt.axis('off')

  plt.tight_layout()
  plt.show()

  img=cv2.imread('/content/246.JPG (1).jpeg',0)
  if img is None:
    print('Error image not found.')

  else:
    sobel_x=cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
    sobel_y=cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)
    sobel=cv2.magnitude(sobel_x,sobel_y)

  kernel_x=np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
  kernel_y=np.array([[-1,0,1],[-2,0,2],[-1,0,1]])

  prewitt_x=cv2.filter2D(img,-1,kernel_x)
  prewitt_y=cv2.filter2D(img,-1,kernel_y)
  prewitt_combined=prewitt_x+prewitt_y

  canny_edges=cv2.Canny(img,100,200)

  show_comparision(img,np.uint8(np.absolute(sobel_combined)),prewitt_combined,canny_edges)

import cv2
import numpy as np
import matplotlib.pyplot as plt


def show_comparison(original, sobel, prewitt, canny):

    plt.figure(figsize=(12, 10))

    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title('Original Grayscale Image')
    plt.axis('off')

    plt.subplot(2, 2, 2)
    plt.imshow(sobel, cmap='gray')
    plt.title('Sobel Edge Detection')
    plt.axis('off')

    plt.subplot(2, 2, 3)
    plt.imshow(prewitt, cmap='gray')
    plt.title('Prewitt Edge Detection')
    plt.axis('off')

    plt.subplot(2, 2, 4)
    plt.imshow(canny, cmap='gray')
    plt.title('Canny Edge Detection')
    plt.axis('off')

    plt.tight_layout()
    plt.show()



img = cv2.imread('/content/observation-urban-building-business-steel_1127-2397 (1)jpg', 0)

if img is None:
    print("Error: Image not found.")
else:


    sobel_x = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

    sobel = cv2.magnitude(sobel_x, sobel_y)
    sobel = np.uint8(np.absolute(sobel))



    kernel_x = np.array([
        [-1, 0, 1],
        [-1, 0, 1],
        [-1, 0, 1]
    ])

    kernel_y = np.array([
        [-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1]
    ])

    prewitt_x = cv2.filter2D(img, cv2.CV_64F, kernel_x)
    prewitt_y = cv2.filter2D(img, cv2.CV_64F, kernel_y)

    prewitt = cv2.magnitude(prewitt_x, prewitt_y)
    prewitt = np.uint8(prewitt)



    canny_edges = cv2.Canny(img, 100, 200)


    show_comparison(
        img,
        sobel,
        prewitt,
        canny_edges
    )